
INSERT INTO `CLAIMS` (`USER_ID`, `CLAIMS_APPLICATION_NO`, `CLAIMS_APPLICATION_TYPE`, `CLAIMS_STATUS`) VALUES ('1', NULL, 'application', '-1');
INSERT INTO `CLAIMS` (`USER_ID`, `CLAIMS_APPLICATION_NO`, `CLAIMS_APPLICATION_TYPE`, `CLAIMS_STATUS`) VALUES ('1', NULL, 'application', '0');
INSERT INTO `CLAIMS` (`USER_ID`, `CLAIMS_APPLICATION_NO`, `CLAIMS_APPLICATION_TYPE`, `CLAIMS_STATUS`) VALUES ('1', NULL, 'application', '1');
INSERT INTO `CLAIMS` (`USER_ID`, `CLAIMS_APPLICATION_NO`, `CLAIMS_APPLICATION_TYPE`, `CLAIMS_STATUS`) VALUES ('1', NULL, 'application', '2');
INSERT INTO `CLAIMS` (`USER_ID`, `CLAIMS_APPLICATION_NO`, `CLAIMS_APPLICATION_TYPE`, `CLAIMS_STATUS`) VALUES ('1', NULL, 'application', '3');
INSERT INTO `CLAIMS` (`USER_ID`, `CLAIMS_APPLICATION_NO`, `CLAIMS_APPLICATION_TYPE`, `CLAIMS_STATUS`) VALUES ('1', NULL, 'application', '4');
INSERT INTO `CLAIMS` (`USER_ID`, `CLAIMS_APPLICATION_NO`, `CLAIMS_APPLICATION_TYPE`, `CLAIMS_STATUS`) VALUES ('1', NULL, 'application', '5');


UPDATE `CLAIMS` SET `CLAIMS_STATUS`= '-1' WHERE `USER_ID` = 1
UPDATE `CLAIMS` SET `CLAIMS_STATUS`= '0' WHERE `USER_ID` = 1
UPDATE `CLAIMS` SET `CLAIMS_STATUS`= '1' WHERE `USER_ID` = 1
UPDATE `CLAIMS` SET `CLAIMS_STATUS`= '2' WHERE `USER_ID` = 1
UPDATE `CLAIMS` SET `CLAIMS_STATUS`= '3' WHERE `USER_ID` = 1
UPDATE `CLAIMS` SET `CLAIMS_STATUS`= '4' WHERE `USER_ID` = 1
UPDATE `CLAIMS` SET `CLAIMS_STATUS`= '5' WHERE `USER_ID` = 1



DELETE FROM `CLAIMS` WHERE `CLAIMS`.`USER_ID` = 1



