
INSERT INTO `app_status` (`USER_ID`, `APP_STATUS_APPLICATION_NO`, `APP_STATUS_STATUS`) VALUES ('1', NULL, '-1');
INSERT INTO `app_status` (`USER_ID`, `APP_STATUS_APPLICATION_NO`, `APP_STATUS_STATUS`) VALUES ('1', NULL, '0');
INSERT INTO `app_status` (`USER_ID`, `APP_STATUS_APPLICATION_NO`, `APP_STATUS_STATUS`) VALUES ('1', NULL, '1');
INSERT INTO `app_status` (`USER_ID`, `APP_STATUS_APPLICATION_NO`, `APP_STATUS_STATUS`) VALUES ('1', NULL, '2');
INSERT INTO `app_status` (`USER_ID`, `APP_STATUS_APPLICATION_NO`, `APP_STATUS_STATUS`) VALUES ('1', NULL, '3');
INSERT INTO `app_status` (`USER_ID`, `APP_STATUS_APPLICATION_NO`, `APP_STATUS_STATUS`) VALUES ('1', NULL, '4');
INSERT INTO `app_status` (`USER_ID`, `APP_STATUS_APPLICATION_NO`, `APP_STATUS_STATUS`) VALUES ('1', NULL, '5');


UPDATE `app_status` SET `APP_STATUS_STATUS`= '-1' WHERE `USER_ID` = 1
UPDATE `app_status` SET `APP_STATUS_STATUS`= '0' WHERE `USER_ID` = 1
UPDATE `app_status` SET `APP_STATUS_STATUS`= '1' WHERE `USER_ID` = 1
UPDATE `app_status` SET `APP_STATUS_STATUS`= '2' WHERE `USER_ID` = 1
UPDATE `app_status` SET `APP_STATUS_STATUS`= '3' WHERE `USER_ID` = 1
UPDATE `app_status` SET `APP_STATUS_STATUS`= '4' WHERE `USER_ID` = 1
UPDATE `app_status` SET `APP_STATUS_STATUS`= '5' WHERE `USER_ID` = 1



DELETE FROM `app_status` WHERE `app_status`.`USER_ID` = 1



